### ISSUE TITLE
Getting headers from request

### ISSUE THREAD

**Issue by jebab** [elm/http#18]
Hi, 

I think elm-http should provide a nice way to get headers from http response, like what is done in : 
http://package.elm-lang.org/packages/jessitron/elm-http-with-headers/latest

Main reason (in my view) is because Rest API uses header Link (http://tools.ietf.org/html/rfc5988#page-6) to handle Pagination, when i want to use elm to acces an RestApi, i need to acces response header.

**Comment by j-panasiuk** [comment]
Hi, jebab!

If you're unable to get access to `Link` response header, make sure that:
1) it is whitelisted in `Access-Control-Expose-Headers` (in case of cross-origin requests), otherwise it wil get blocked by the browser (even if visible in dev-tools!)
2) it is actually exposed as "Link" and not something else. In my case I was using json-server, which probably by mistake exposes "Links" header instead: https://github.com/typicode/json-server/pull/381/files
After renaming "Links" to "Link" in json-server source the header became accessible

In any case, `Link` can be accessed like any other header under elm-http (XMLHttpRequest getAllResponseHeaders() method is used under the hood)

(Hope that helps someone with similar issues)

**Comment by evancz** [comment]
I think most people do not need this by default. If you are in a more complex situation, you will probably have the necessary conceptual scaffolding to either (1) extract them directly or (2) find a library like the one you mention. I find that more complex situations often lead to me customizing how my HTTP requests work quite a bit, so I don't think this is out of line with the intended path from beginner to advanced.
