### ISSUE TITLE
Progress demo not working

### ISSUE THREAD

**Issue by swordbeta** [elm/http#36]
The progress demo that can be found [here](https://hirafuji.com.br/elm/http-progress-example/) does not work;

![screenshot from 2017-11-08 23-03-42](https://user-images.githubusercontent.com/7511094/32577090-16f30ef6-c4d9-11e7-891f-366cf30e7c73.png)

**Comment by pablohirafuji** [comment]
The progress demo needs the server to serve the content without compression/gzip. I no longer have the ftp that I used to serve the uncompressed content.

**Comment by pablohirafuji** [comment]
I updated the example and moved it to GitHub: https://github.com/pablohirafuji/elm-http-progress-example. Also added a note about the lack of support of this feature when the content is gzipped.

**Comment by pablohirafuji** [comment]
The issue is: chrome and others browsers does not implement tracking progress when the content is gzipped because the specs are unclear whether the value of the `content-length` header should be after-decoding or before-decoding. More details at https://bugs.chromium.org/p/chromium/issues/detail?id=463622.

**Comment by evancz** [comment]
There are new examples of using tracking progress over here: https://github.com/elm/file/tree/master/examples

They should work better. I see notes about the gzip issue online in various places though, so that part may still be odd.
